/**
 * Generated by scripts/sync-chains.mjs. Do not edit by hand.
 *
 * Run `pnpm sync:chains` against a checkout of Zunia-Lab/zunia-chain-registry
 * to refresh the names, the logos in public/chains and the counts below.
 */

import type { ChainEntry } from "./site";

export const CHAINS: ChainEntry[] = [
  { chainId: "safrochain-1", name: "Safrochain", logo: "/chains/safrochain-1.png", home: true },
  { chainId: "cosmoshub-4", name: "Cosmos Hub", logo: "/chains/cosmoshub-4.png" },
  { chainId: "osmosis-1", name: "Osmosis", logo: "/chains/osmosis-1.png" },
  { chainId: "celestia", name: "Celestia", logo: "/chains/celestia.png" },
  { chainId: "neutron-1", name: "Neutron", logo: "/chains/neutron-1.png" },
  { chainId: "injective-1", name: "Injective", logo: "/chains/injective-1.png" },
  { chainId: "dydx-mainnet-1", name: "dYdX", logo: "/chains/dydx-mainnet-1.png" },
  { chainId: "stride-1", name: "Stride", logo: "/chains/stride-1.png" },
  { chainId: "juno-1", name: "Juno", logo: "/chains/juno-1.png" },
  { chainId: "akashnet-2", name: "Akash", logo: "/chains/akashnet-2.png" },
  { chainId: "noble-1", name: "Noble", logo: "/chains/noble-1.png" },
  { chainId: "axelar-dojo-1", name: "Axelar", logo: "/chains/axelar-dojo-1.png" },
  { chainId: "kaiyo-1", name: "Kujira", logo: "/chains/kaiyo-1.png" },
  { chainId: "phoenix-1", name: "Terra", logo: "/chains/phoenix-1.png" },
  { chainId: "pacific-1", name: "Sei", logo: "/chains/pacific-1.png" },
  { chainId: "archway-1", name: "Archway", logo: "/chains/archway-1.png" },
];

/** Mainnet entries in the registry, excluding testnets and hidden chains. */
export const REGISTRY_STATS = {
  cosmos: 218,
  evm: 43,
  svm: 1,
  mainnet: 262,
} as const;
